Repository nearform/fast-jwt, pull requests merged in 2025-02, with the labels that each got.

#546 chore: add type for cacheKeyBuilder
  src/index.d.ts
  test/types.spec.ts
Labels: size:S, lgtm

#548 Mitata benchmark
  README.md
  benchmarks/README.md
  benchmarks/auth0.mjs
  benchmarks/decode.mjs
  benchmarks/sign.mjs
  benchmarks/update_benchmarks.mjs
  benchmarks/utils.mjs
  benchmarks/verify.mjs
  package.json
Labels: documentation, size:XL, lgtm

#535 Fix benchmarks with regards to jsonwebtoken performance
  benchmarks/README.md
  benchmarks/sign.mjs
  benchmarks/utils.mjs
  benchmarks/verify.mjs
Labels: size:XL, lgtm
